### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by iRobbedNitreo** [Vedzaa/NitroSniperGo#13]
after latest update seem to be receiving this error 
![image](https://user-images.githubusercontent.com/70293518/91356548-c235f880-e7e7-11ea-9c1d-9e5307030944.png)

also receive errors with python one.

syntaxerror non ascii character \xa3

**Comment by Vedzaa** [comment]
Can you give me your discord, so we can figure out where this error come from ?

**Comment by iRobbedNitreo** [comment]
Czpi#6086

**Comment by Vedzaa** [comment]
Just remove line 64 to 73 if you have this problem or `iconv -f utf-8 -t utf-8 -c sniper.go > temp.go && mv temp.go sniper.go`
