### ISSUE TITLE
stop DM giveaway host !

### ISSUE THREAD

**Issue by dLayed** [Vedzaa/NitroSniperGo#15]
please do something to stop DM giveaway host

**Comment by Vedzaa** [comment]
remove line 245 to 265

**Comment by dLayed** [comment]
thanks

**Comment by dLayed** [comment]
If you can make it some more fast btw it works great

**Comment by Vedzaa** [comment]
If you want the bot to send DM or join giveaway faster just edit `time.Sleep`
