### ISSUE TITLE
Your current release picture on your readme isn´t showing the release for your repo

### ISSUE THREAD

**Issue by PeterStrick** [Vedzaa/NitroSniperGo#16]
It is showing the latest release tag for https://github.com/Naereen/StrapDown.js which is on 1.1.1

Change this code:

` [![GitHub release](https://img.shields.io/github/release/Naereen/StrapDown.js.svg)](https://github.com/Vedzaa/NitroSniperGo/releases) `

To this instead:

` [![GitHub release](https://img.shields.io/github/release/Vedzaa/NitroSniperGo.svg)](https://github.com/Vedzaa/NitroSniperGo/releases) `

It will look now like this: [![GitHub release](https://img.shields.io/github/release/Vedzaa/NitroSniperGo.svg)](https://github.com/Vedzaa/NitroSniperGo/releases)

Instead of this: [![GitHub release](https://img.shields.io/github/release/Naereen/StrapDown.js.svg)](https://github.com/Vedzaa/NitroSniperGo/releases)

**Comment by Vedzaa** [comment]
Thank you very much !
