### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by Wacomoley** [Vedzaa/NitroSniperGo#18]
At first my anti virus wouldn't let me run it so i added an exception, but after than when i would try to run it it would show the Discord Sniper logo then close immediately after. I'm not sure why, i have pasted the token in the correct place.

**Comment by Vedzaa** [comment]
Hi, did you put your token between the " ?

**Comment by Wacomoley** [comment]
Yeah I did, I even re-copied it to make sure it was right, still crashed on
boot

**Comment by Vedzaa** [comment]
Can you run it from cmd to see the error pls ?

**Comment by Wacomoley** [comment]
Nevermind I got it, I placed the token where "token" was and not where the
"" were
