### ISSUE TITLE
malformed output when using screen

### ISSUE THREAD

**Issue by iraizo** [Vedzaa/NitroSniperGo#19]
<image src="https://files.httpreq.club/48"></img>
A small bug i guess. I used `screen ./NitroSniperGo`

**Comment by Vedzaa** [comment]
I think you don't have the font installed on your VPS or on the pc you're running termius (I think?) on.

**Comment by iraizo** [comment]
False, it works when running it natively without screen

**Comment by Vedzaa** [comment]
I don't know why this happens but don't you think it would be better to use nohup instead ?

**Comment by iraizo** [comment]
No clue, I either use screen or tmux I just wanted you to inform you about it

**Comment by Vedzaa** [comment]
This problem definitely comes from your pc. nohup will make it run forever, you can redirect output to a file to keep logs, and maybe you won't have this problem.

**Comment by iraizo** [comment]
tested it on 3 different machines but okay
