### ISSUE TITLE
Unmarshlling issue.

### ISSUE THREAD

**Issue by RinseWash** [Vedzaa/NitroSniperGo#2]
[DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string

This message appears during start-up, it doesn't look like it hinders any functions but how do I fix this?

**Comment by Vedzaa** [comment]
This error seems to come from the library discordgo that I use. I don't know how to fix it then as it's not my code, sorry.

**Comment by goldentg** [comment]
same error
