### ISSUE TITLE
Option to turn the Giveaway Joiner on or off

### ISSUE THREAD

**Issue by Overimaginer** [Vedzaa/NitroSniperGo#22]
Title basically explains it, this would be in the same where we place our token.

**Comment by Vedzaa** [comment]
Thanks for your suggestion, I might do that as well as other little things when I have time to do it.

**Comment by Vedzaa** [comment]
If you don't want to join giveaways you can also compile yourself this version 6d7442be89a6ba0c2d381b862a6bf94d7942bd1e, I personally use this one
