### ISSUE TITLE
Display how much time it took to snipe a Nitro code/giveaway

### ISSUE THREAD

**Issue by Overimaginer** [Vedzaa/NitroSniperGo#23]

**Comment by Vedzaa** [comment]
Adding new function calls will make it a bit slower, which is not the point of the program

**Comment by Vedzaa** [comment]
If you don't want to join giveaways you can also compile yourself this version 6d7442be89a6ba0c2d381b862a6bf94d7942bd1e, I personally use this one

**Comment by MXNTE666** [comment]
you can do this really easily by changing all likes of this:
magenta.Print(time.Now().Format("15:04:05 "))

to this

magenta.Print(time.Now().Format("15:04:05.000000 "))

you're just going to need a calculator to calculate the difference between times.

**Comment by Vedzaa** [comment]
If you read the code carefully you'll see that I print timestamp after doing the request.

**Comment by MXNTE666** [comment]
Yeah, I know, but the timestamp you used prints Hours, Minutes & Seconds. The difference I made was to print into Hours, Minutes & Microseconds.

**Comment by MXNTE666** [comment]
I only did this because the sniper on my 10gig literally snipes in and around 30-40microseconds haha

**Comment by Vedzaa** [comment]
I know but you won't be able to see the time it takes even if you print microseconds.

**Comment by MXNTE666** [comment]
Oh I could be wrong then lol. Is the difference in these 2 times, not the time it takes to snipe a code? 

https://i.imgur.com/7VOOXAz.png

**Comment by Vedzaa** [comment]
This time is not relevant as it should be the difference between reading the message and having the result. But instead it read message > parse code > send request > read result > 1st print > analyse result > print 2nd request

**Comment by MXNTE666** [comment]
Ahhhh okay, my bad. How would you go about this then?

**Comment by Vedzaa** [comment]
You can do something like this but it might make the sniper slower
```go
...
func messageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {
	var firstTime = time.Now()
	if re.Match([]byte(m.Content)) && SniperRunning {
		code := re.FindStringSubmatch(m.Content)

		if len(code) < 2 {
			return
		}

		if len(code[2]) < 16 {
			_, _ = magenta.Print(time.Now().Format("15:04:05 "))
			_, _ = red.Print("[=] Auto-detected a fake code: ")
			_, _ = red.Print(code[2])
			fmt.Println(" from " + m.Author.String())
			return
		}

		var strRequestURI = []byte("https://discordapp.com/api/v6/entitlements/gift-codes/" + code[2] + "/redeem")
		req := fasthttp.AcquireRequest()
		req.Header.SetContentType("application/json")
		req.Header.Set("authorization", Token)
		req.SetBody([]byte(`{"channel_id":` + m.ChannelID + "}"))
		req.Header.SetMethodBytes(strPost)
		req.SetRequestURIBytes(strRequestURI)
		res := fasthttp.AcquireResponse()

		if err := fasthttp.Do(req, res); err != nil {
			panic("handle error")
		}

		fasthttp.ReleaseRequest(req)

		body := res.Body()

		bodyString := string(body)
		fasthttp.ReleaseResponse(res)

		_, _ = magenta.Print(firstTime.Format("15:04:05.000000 "))
		_, _ = green.Print("[-] Sniped code: ")
		_, _ = red.Print(code[2])
...
```

**Comment by MXNTE666** [comment]
so then this displays the time you need to calculate the difference correctly?

**Comment by Vedzaa** [comment]
Exactly, you can also do it programmatically but I'm working on something else rn

**Comment by MXNTE666** [comment]
that works perfectly. Thanks a mil!
