### ISSUE TITLE
go

### ISSUE THREAD

**Issue by whislol** [Vedzaa/NitroSniperGo#24]
when using go, what do i need to run it. ive been trying to download but it hasnt been working and or cant find the right download

**Comment by Vedzaa** [comment]
Can you give me your discord pls ?

**Comment by whislol** [comment]
Whis#6969

**Comment by Vedzaa** [comment]
It says that you do not accept friend requests

**Comment by whislol** [comment]
whats yours?

**Comment by Vedzaa** [comment]
sry I won't give it here as I would get too many friends requests

**Comment by whislol** [comment]
alright let me change my settings add me in 2 minutes

**Comment by whislol** [comment]
can you add my new discord and give me the theother file called nitro sniper go build or whatever Whis#6810

**Comment by Vedzaa** [comment]
https://github.com/Vedzaa/NitroSniperGo/releases
