### ISSUE TITLE
Discord Servers for giveaways

### ISSUE THREAD

**Issue by Bango88** [Vedzaa/NitroSniperGo#26]
what discord servers do you recommend for sniping?

**Comment by PeterStrick** [comment]
Mostly Servers that provide Emojis/Giveaways are your best bet.
But I also got some look with YouTuber/Twitch Streamer Discord Servers and others.
Personally I am in 58 Discord Servers and let the Sniper run while im asleep.
I´ll usually successfully snipe Nitro in a 1/18 chance everytime. So it takes some time until you got nitro.
