### ISSUE TITLE
Disable giveaway sniper

### ISSUE THREAD

**Issue by UltraTV** [Vedzaa/NitroSniperGo#27]
I'm forced using an old version, because I don't want the giveaway sniper.
Is it possible to make an version without it, or maybe a toggle for it?

**Comment by Vedzaa** [comment]
I also use an old version and this is definitely the next thing I'll add. But unfortunately I don't have time now as I have a lot of school, personal and professional projects to do. I'll add it as soon as I can

**Comment by Vedzaa** [comment]
Done fe1fd0b9014e2e973c9936c90c52557be961b1dd
