### ISSUE TITLE
Is it possible to not be 24/7 online?

### ISSUE THREAD

**Issue by UltraTV** [Vedzaa/NitroSniperGo#28]
With the sniper running, I'm always online, it doesn't matter if I close discord on my pc.
Is it possible to show as offline, when I close discord with the bot running?

**Comment by PeterStrick** [comment]
@UltraTV I don´t think theres a way for the sniper to show you as offline, but you can let discord run in the background and set your visibility as offline, while the sniper is running.

Example: (sorry for german but you know what I mean
![image](https://user-images.githubusercontent.com/60312421/94893703-1cca1080-0488-11eb-957d-76d70a615219.png)

**Comment by UltraTV** [comment]
> @UltraTV I don´t think theres a way for the sniper to show you as offline, but you can let discord run in the background and set your visibility as offline, while the sniper is running.
> 
> Example: (sorry for german but you know what I mean)
> ![image](https://user-images.githubusercontent.com/60312421/94893703-1cca1080-0488-11eb-957d-76d70a615219.png)

It's not a problem, I'm native german too.
So I need to always manually set myself as offline?

**Comment by Vedzaa** [comment]
Thanks, @PeterStrick, for helping me with issues ! I saw on discord API that we can change status. I'll check later if it's implemented in discordgo and will add this feature in the next version if possible. Thanks for the suggestion @UltraTV

**Comment by PeterStrick** [comment]
> Thanks, @PeterStrick, for helping me with issues ! I saw on discord API that we can change status. I'll check later if it's implemented in discordgo and will add this feature in the next version if possible. Thanks for the suggestion @UltraTV

No problem. I´ll help with issues if I have the time to do so anytime!
