### ISSUE TITLE
HEllo please tell me how to work this

### ISSUE THREAD

**Issue by Rayyan2650** [Vedzaa/NitroSniperGo#29]
![image](https://user-images.githubusercontent.com/59572861/94950940-d9f65000-04fc-11eb-8d1d-31cb210e4862.png)
Just tell me what to do next please I downloaded i need help!

**Comment by Rayyan2650** [comment]
what to do next i also added my token in settings.json now what?

**Comment by Vedzaa** [comment]
Hi, download this instead https://github.com/Vedzaa/NitroSniperGo/releases/tag/v1.2.
Then put your token in settings.json and run the .exe
