### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Motzumoto** [Vedzaa/NitroSniperGo#4]
Most servers now are bypassing nitro snipers by just sending the code of the gift, for instance; discord.gift/guw3498g
They are sending `guw3498g` of the gift code by its self to bypass snipers, it would be cool if this sniper could find random strings of numbers and letters and attempt to claim it by adding the `discord.gift/` to it.

**Comment by Vedzaa** [comment]
Thanks for your suggestion, I can do this with the length of a code but it might trigger false positives and result in a ban of your account because of the number of requests made. If you have an account that can be banned add give me your discord and I will send a version with this feature.

**Comment by Motzumoto** [comment]
Here is one of my account's ID's: 638377552964091944

**Comment by Vedzaa** [comment]
Sent a custom version and doesn't seem conclusive
